var fs = require("fs");
var fp = "d:/Projects/hire_adda/frontend/src/constants/suggestions.ts";
var c = fs.readFileSync(fp, "utf8");

function ex(c, name, items) {
  var ds = c.indexOf("export const " + name + " = [");
  if (ds === -1) { console.error("NOT FOUND: " + name); return c; }
  var ci = c.indexOf("] as const;", ds);
  if (ci === -1) { console.error("NO CLOSE: " + name); return c; }
  var ac = c.substring(ds, ci);
  var existing = new Set();
  var r = /'([^']+)'/g;
  var m;
  while (m = r.exec(ac)) existing.add(m[1]);
  var u = items.filter(function(i) { return existing.has(i) === false; });
  if (u.length === 0) { console.log(name + ": 0 new"); return c; }
  var ins = u.map(function(i) { return "  '" + i + "',"; }).join(String.fromCharCode(10)) + String.fromCharCode(10);
  c = c.substring(0, ci) + ins + c.substring(ci);
  console.log(name + ": +" + u.length);
  return c;
}
c = ex(c, "DEPARTMENT_SUGGESTIONS", ["Compliance","Internal Audit","Risk Management","Corporate Strategy","Business Intelligence","Data Science","Cybersecurity","Infrastructure","Platform Engineering","Mobile Development","QA & Testing","Release Management","Solution Architecture","Enterprise Architecture","Technical Writing","Customer Experience","Field Sales","Channel Sales","Inside Sales","Partnerships","Alliances","Government Relations","Public Affairs","Investor Relations","Mergers & Acquisitions","Treasury","Taxation","Company Secretarial","Real Estate","Facilities","Safety & Environment","Quality Assurance","Production","Plant Operations","Maintenance","Packaging","Logistics","Warehouse","Fleet Management"]);
c = ex(c, "ROLE_CATEGORY_SUGGESTIONS", ["IT Software","IT Hardware","IT Networking","IT Security","Web Development","Game Development","ERP/CRM","Data Science & Analytics","AI & ML","Cloud & DevOps","Program Management","Agile Coach","Systems Analysis","UX Writing","Content Design","Brand Management","Trade Marketing","Category Management","Visual Merchandising","E-commerce","Marketplace Management","Affiliate Marketing","Influencer Marketing","PR & Communications","Corporate Communications","Internal Communications","Event Management","Hospitality Management","Travel & Tourism","Airlines","Shipping & Maritime","Port Operations","Customs & Clearance","Import/Export","International Trade","Forex & Treasury","Collections","Underwriting","Claims Processing","Actuarial","Fund Management","Fixed Income","Derivatives","Commodity Trading","Real Estate Broking","Property Management","Facility Management","Security & Surveillance","Fire Safety","Environmental Health & Safety","Clinical Research","Drug Safety","Medical Affairs","Regulatory Affairs","Quality Control","Quality Assurance (Pharma)","Formulation Development","API Manufacturing","Bioprocess Engineering","Medical Coding","Medical Billing","Health Informatics","Hospital Administration","Nursing Administration","Radiology","Pathology","Anesthesiology","Teaching Faculty","Academic Administration","Examination","Admissions","Placement","Curriculum Development","Library Science","Sports Coaching","Fashion Design","Textile Design","Interior Design","Architecture","Urban Planning","Landscape Architecture","Civil Engineering","Structural Engineering","MEP Engineering","Construction Management","Quantity Surveying","Mining Engineering","Petroleum Engineering","Geology","Metallurgy","Ceramics","Polymer Technology"]);
c = ex(c, "DEGREE_SUGGESTIONS", ["B.Sc. (Hons)","M.Sc. (Hons)","B.Com (Hons)","M.Com","BBS","BBM","M.Voc","Integrated M.Sc","M.Des","MFA","M.Arch","BPlan","MPlan","MDS","M.Pharm","Pharm.D","MPT","BOT","M.Sc Nursing","GNM","ANM","DMLT","BVSc","MVSc","M.Ed","D.El.Ed","M.Lib","B.P.Ed","M.P.Ed","BHM","BHMCT","Diploma in Engineering","PGDBM","PGDCA","PGDHRM","Executive PGP","Fellow Programme (FPM)","LLB (3-year)","LLB (5-year)","LLM","BGL","BL","Company Secretary (CS)","Chartered Accountancy (CA)","CMA (India)"]);
c = ex(c, "FIELD_OF_STUDY_SUGGESTIONS", ["Ceramic Engineering","Food Technology","Genetic Engineering","Naval Architecture","Power Engineering","Tool Engineering","Applied Physics","Applied Chemistry","Forensic Science","Microbiology","Zoology","Botany","Genetics","Molecular Biology","Nutrition & Dietetics","Home Science","Geography","History","Political Science","Sociology","Anthropology","Archaeology","Sanskrit","Hindi Literature","English Literature","Tamil Literature","Journalism","Mass Communication","Film Studies","Theatre Arts","Music","Dance","Fine Arts","Applied Arts","Sculpture","Photography","Animation & Multimedia","Fashion Technology","Apparel Design","Leather Technology","Printing Technology","Library & Information Science","Physical Education","Yoga","Naturopathy","Occupational Therapy","Speech Therapy","Optometry","Audiology","Prosthetics & Orthotics","Hospital Administration","Public Health","Epidemiology","Biostatistics","Health Economics"]);
c = ex(c, "LANGUAGE_SUGGESTIONS", ["Bodo","Dogri","Maithili","Santali","Sindhi","Kashmiri","Tulu","Bhojpuri","Chhattisgarhi","Rajasthani","Haryanvi","Magahi","Marwari","Cantonese","Thai","Vietnamese","Bahasa Indonesia","Bahasa Malay","Swahili","Amharic","Farsi","Pashto","Burmese","Khmer","Sinhala","Tagalog","Dutch","Polish","Turkish","Hebrew","Greek","Czech","Hungarian","Romanian","Swedish","Norwegian","Danish","Finnish"]);
c = ex(c, "BENEFIT_SUGGESTIONS", ["Mental Health Coverage","Therapy/Counseling Benefits","Employee Assistance Program","Sabbatical Leave","Adoption Assistance","Surrogacy Benefits","Fertility Treatment Coverage","Gender Transition Support","Pet Insurance","Pet-Friendly Office","Standing Desk","Ergonomic Equipment","Home Office Setup Allowance","Internet Reimbursement","Phone Reimbursement","Car Lease/Allowance","Company Car","Fuel Card","Parking Subsidy","Relocation Package","Housing Assistance","Sodexo Meal Card","Cafeteria Subsidy","Night Shift Allowance","Overtime Pay","Spot Awards","Long Service Award","Patent Bonus","Referral Bonus","ESOP/RSU","National Pension Scheme (NPS) Contribution","Superannuation Fund","Leave Travel Allowance (LTA)","Leave Encashment","Compensatory Off","Birthday Leave","Volunteer Day Off","Paternity Leave (Enhanced)","Maternity Leave (Enhanced)","Flexi Hours","4-Day Work Week"]);
c = ex(c, "VOLUNTEER_CAUSE_SUGGESTIONS", ["Rural Development","Women Empowerment","Digital Literacy","Clean Water","Sanitation","Tribal Welfare","Elderly Care","Blood Donation","Organ Donation","Road Safety","Waste Management","Renewable Energy Advocacy","Open Source","Coding for Kids","Career Mentoring","Financial Literacy","Anti-Corruption","Consumer Rights","Legal Aid","Disaster Preparedness"]);
c = ex(c, "HOBBY_SUGGESTIONS", ["Photography","Birdwatching","Astronomy","Woodworking","Pottery","Calligraphy","Origami","Sudoku","Crossword","Chess","Carrom","Cricket","Badminton","Table Tennis","Swimming","Cycling","Trekking","Rock Climbing","Scuba Diving","Paragliding","Skydiving","Kayaking","Surfing","Marathon Running","Yoga","Meditation","Martial Arts","Boxing","Fencing","Archery","Horse Riding","Golf","Skating","Skateboarding","Bowling","Billiards","Darts","Card Games","Board Games","Anime","Manga","Cosplay","Vlogging","Podcasting","Blogging","DIY Electronics","3D Printing","Drone Flying","Gardening","Bonsai"]);
c = ex(c, "INTEREST_SUGGESTIONS", ["Sustainability","Climate Tech","Social Entrepreneurship","Impact Investing","Circular Economy","Smart Cities","Urban Farming","Space Technology","Quantum Computing","Biotech","Neuroscience","Philosophy","Psychology","Behavioral Economics","Geopolitics","Foreign Policy","Defense Technology","Aerospace","Autonomous Vehicles","Electric Vehicles","Renewable Energy","Carbon Markets","Crypto/DeFi","DAOs","Metaverse","Digital Art","NFTs","Generative AI","EdTech","HealthTech","AgriTech","FinTech","PropTech","LegalTech","FoodTech","GovTech","CleanTech","DeepTech","SpaceTech"]);
c = ex(c, "PROFESSIONAL_ORGANIZATION_SUGGESTIONS", ["ASSOCHAM","IMA (Indian Medical Association)","BCI (Bar Council of India)","ICAI (Chartered Accountants)","ICSI (Company Secretaries)","ICMAI (Cost Accountants)","Institution of Engineers India","Indian Society of Mechanical Engineers","Computer Society of India","Indian Pharmaceutical Association","Medical Council of India","Dental Council of India","Pharmacy Council","Nursing Council","All India Management Association","National HRD Network","SHRM India","ISA (Indian Staffing Association)","Indian Merchants Chamber","PHD Chamber","MCCI","BCCI (Bombay Chamber)","TiE","iSPIRT"]);
c = ex(c, "TEST_SCORE_SUGGESTIONS", ["GATE CS","GATE EC","GATE ME","GATE EE","GATE CE","GATE CH","GATE IN","GATE XL","GATE PI","ATMA","NEET UG","NEET PG","UPSC CSE","UPSC IES","UPSC CMS","SSC CGL","SSC CHSL","RRB NTPC","IBPS PO","IBPS Clerk","SBI PO","RBI Grade B","NABARD","SEBI Grade A","SET","CLAT","AILET","LSAT India","TISSNET","MICAT","IIFT","COMEDK","WBJEE","MHT CET","AP EAMCET","TS EAMCET","KCET"]);
c = ex(c, "SUB_INDUSTRY_SUGGESTIONS", ["Automotive Components","Heavy Engineering","Light Engineering","Industrial Automation","Precision Manufacturing","Electronics Manufacturing","Textile Manufacturing","Chemical Processing","Pharmaceutical Manufacturing","Food & Beverage Manufacturing","Packaging Manufacturing","Plastic & Rubber","Retail Banking","Corporate Banking","Investment Banking","Asset Management","Microfinance","NBFC","Stock Broking","Commodity Trading","Credit Rating","Payment Processing","Hospital Chains","Diagnostics","Home Healthcare","Medical Tourism","Pharmaceutical R&D","Clinical Trials","Solar Energy","Wind Energy","EV Charging","Battery Technology","Oil Refining","Gas Distribution","Power Generation","Power Distribution","Digital Publishing","Podcast Network","Influencer Economy","Esports","Animation Studio","VFX Studio","Music Streaming","Video Streaming"]);
c = ex(c, "INVESTOR_SUGGESTIONS", ["Accel India","Sequoia Capital India (Peak XV)","Iron Pillar","Norwest Venture Partners","General Atlantic India","Warburg Pincus India","KKR India","Blackstone India","Temasek India","GIC India","Premji Invest","Ratan Tata (Angel)","Kunal Shah (Angel)","Nithin Kamath (Angel)","Anupam Mittal (Angel)","Prosus","Naspers","Info Edge Ventures","Bessemer Venture Partners","Alpha Wave Global","Omidyar Network India","Multiples Alternate","ICICI Venture","Zodius Capital","Helion Venture Partners","Saama Capital","Eight Roads Ventures","Bertelsmann India","Fundamentum Partnership","WaterBridge Ventures"]);
c = ex(c, "NATIONALITY_SUGGESTIONS", ["Mexican","Argentine","Colombian","Turkish","Egyptian","Nigerian","Kenyan","Ghanaian","Ethiopian","Tanzanian","Ugandan","Moroccan","Tunisian","Qatari","Kuwaiti","Omani","Bahraini","Jordanian","Lebanese","Iranian","Iraqi","Afghan","Myanmarese","Cambodian","Laotian","Taiwanese","Hong Konger","Portuguese","Greek","Polish","Czech","Hungarian","Romanian","Ukrainian","Norwegian","Danish","Finnish","Belgian","Austrian","Chilean","Peruvian","Venezuelan","Ecuadorian","Uruguayan","Cuban","Jamaican","Trinidadian"]);
c = ex(c, "COUNTRY_SUGGESTIONS", ["Colombia","Peru","Ukraine","Romania","Hungary","Greece","Croatia","Serbia","Bulgaria","Slovakia","Slovenia","Lithuania","Latvia","Estonia","Luxembourg","Iceland","Malta","Cyprus","Jordan","Lebanon","Iran","Iraq","Morocco","Tunisia","Ghana","Tanzania","Ethiopia","Uganda","Myanmar","Cambodia","Laos","Mongolia","Uzbekistan","Kazakhstan","Maldives","Bhutan","Afghanistan","Cuba","Ecuador","Venezuela","Uruguay","Paraguay","Bolivia","Panama","Costa Rica","Jamaica","Trinidad and Tobago","Mauritius","Fiji","Papua New Guinea"]);
c = ex(c, "PUBLISHER_SUGGESTIONS", ["ACS Publications","AIP Publishing","Annual Reviews","BioMed Central","BMJ Publishing","De Gruyter","Frontiers","Hindawi","Karger","Lippincott Williams & Wilkins","PLoS","Science (AAAS)","Thieme","World Scientific","Cengage Learning","Routledge","Bloomsbury Academic","Palgrave Macmillan","Academic Press","CRC Press","MIT Press","Princeton University Press","Harvard University Press","Stanford University Press","University of Chicago Press"]);
c = ex(c, "ERG_SUGGESTIONS", ["Parents Network","Military Veterans","Neurodiversity","Caregivers","Remote Workers","First Generation Professionals","Interfaith","Multicultural","Pan-African","South Asian","East Asian","Latin American","Indigenous Peoples","Chronic Illness/Invisible Disabilities","Returnship/Career Returners"]);
c = ex(c, "REVENUE_RANGE_OPTIONS", ["₹5000 - ₹10000 Crore","₹10000+ Crore","$0 - 1M","$1 - 10M","$10 - 50M","$50 - 100M","$100 - 500M","$500M - 1B","$1B+"]);
c = ex(c, "VISA_STATUS_OPTIONS", ["Dependent Visa","Business Visa","Employment Visa","Diplomatic Visa","Investor Visa","Transit Visa"]);
c = ex(c, "CORE_VALUE_SUGGESTIONS", ["Customer Obsession","Bias for Action","Frugality","Earn Trust","Deliver Results","Think Big","Learn and Be Curious","Disagree and Commit","Move Fast","Be Bold","Focus on Impact","Build Social Value","Ship It","Data-Driven","Radical Candor","Servant Leadership","Psychological Safety","Growth Mindset","Continuous Improvement"]);
fs.writeFileSync(fp, c);
console.log("Done. Lines: " + c.split(String.fromCharCode(10)).length);


