# ============================================================
# SealedSecret — Backup R2 Credentials
# ============================================================
# Cloudflare R2 credentials for backup CronJobs (db, redis, opensearch).
# Regenerate: kubeseal on VPS with --controller-name sealed-secrets-controller
# ============================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-r2-credentials
  namespace: hire-adda
  labels:
    app: backups
    app.kubernetes.io/name: backups
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: hire-adda
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBwmv774+CSaI0ZnqwGRLS69T2OP8sSRZBw4Bbsb0yRFPdeCNU0ZdsfaFMoiYfAE0K26WO52rvaXCboSVmX66eRNT89Wj6VSai95DBdwVm7aMJYVeB+jYMOzEYSgXi9BXmEwKBmnfCQ3I6pnCT4Jx8oymgSemqx6Tz4RRJJV/Y95NC30UatWO7zcwyrCOiqqyVbAENkQb8GdW+HJUzwlwbD7E4jCwHt+XaWXe4cJpOxyhv7fLc03YKmSO32YFw/KNM32rAeVJyJzdBXWIReWGiO0RR65q6nX+86ENp75jvFomAXy45789sXBsJ7qyWafSAJi5X3v8kh5rAbSWT/9TzwHKNXaeMRO8Ax7I1R7jGZoASVdPauGI4/AIc+xyDjcHW1suiokHuE1luDW0Hb6orTP6l85aR2iW51d7ukG03/6VPiEuT85NcQeuJEhNoOaxuWnfO8p1DZni+f8ecQXfvp4rEvwglf/OCs8nRfrtU5L5h1u4+U6KHX2zuVA7ujasOFYAzza0hgIp6w5QcNbsYwMPpRBohMWUHBzqlDIGOAlcZSKYDu8hXMwfz9CYIcSY8n+ufbz/q2mAPp7nA4vjx9riPuHqI5akkhBd8wDhibwSG/wZV6ujMWhtuHG696Yl+aqztSqNjXQ+GEcnAo7B3F9pHfpehP9RJIv5G0k/wOHF4HqNE6m9JMQG1JQaNNPX7iSTa5irD83NkfNAX1s86YTeyRZKr0dB86C3BLgjgg5g==
    AWS_SECRET_ACCESS_KEY: AgCpmUBT+eHIiWVqlcKBYVKiv9lx4qefbtWWjYLda7CMzymDI5adg6fd8eNi7kLnqB3JwsqS76oCCh4xi0NpC/AzvRnARcN/9vS4k57IJHY0S63mLW0EXx+YumBJHL/B6Z/ftnK82nZBEsjyBBJTM0xjuuyX5bHfXOMSozQsnjNi6olLeuU9zo5PU/w4WcfU5LzVvlmsI+ZpQYOmcRTt5Ia0R+RQllADWit1Nl4ubC9C8ayPeoV953cd3XWobd/FpITYQrF4uihP4kN740F0T8QGwxjwrHSI+UhxtTJ6TnkxUZ3bTZX9DvjAgd6AwA59L9dUFouegN6q4UHqIbSnVOVKlhFa834NshaipOQL6idUd6V2+5hVgM27gr4CfAkVfXVCj/tp6lqwEb0nDgcSggB34+mnnMFuR8/kMn0S1gFRDuhozL0c2o5SCkr25980NZX8GPgnbqhWlgSFTcuzXCvSq6Uxe8HHW77Xz2ipi9zZmO6MBQ+71KPXuRY3OsBmdn6ttl/hd3Rydceube1MihBbZIikPYUFexLj+xW8C7qnHrBTD15c/EZvat2bMIcKWhkq0k659OBsh/NEja5EzT7hgenDsKpla3eFZ2iIAcMP82woKQ5Q+kAfKJIuYaW4Esszqq7kcg6jlgkwgvLSocmYGa6Yqav89yzvcTrtKQJvhbJVU8WQBT3hUFdjA5RnT1Q9bCNPoZrw6BoFXlGixBSIUSP8hKCG47arVfrKhZ1Sce2blV6fWCUEyh5SUDwZl5qSVoRZUA1Yn7hEOuTJ7svS
  template:
    metadata:
      name: backup-r2-credentials
      namespace: hire-adda
      labels:
        app: backups
        app.kubernetes.io/name: backups
        app.kubernetes.io/component: backup
        app.kubernetes.io/part-of: hire-adda
    type: Opaque
