# ============================================================
# SealedSecret Template — OTel Collector Secrets
# ============================================================
# Source of truth: infra/docker/.env (HONEYCOMB_API_KEY)
# Regenerate: infra/scripts/sealed-secret-create.sh
# ============================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-secrets
  namespace: monitoring
  labels:
    app: otel-collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: hire-adda
spec:
  encryptedData:
    HONEYCOMB_API_KEY: AgAgKVz9JzwGSPAiZakj1cL7rU1Fhg7SlBS8rF1naDVam98c699s01aCAtFg75TqZ3mENwBUl6FV1lACOvsMZXiPqzOIoy8cer+IWIkyH7mlYZplYf52k9cVSlse+eh7jykGvOJotwEgXxPt7Vw/e2AiqR6E98S2V/mOByqPnZtNVaH51VchlieuqRtKsEhedUYC3nKo80NigZvh9P52svWIm7zsBrFWnqhQjYEddSPc8q/4CV/97YpJCzc8otdONoguBWO/BDARE+5/F63crvQVEMK6W94teFiie12TOagjHgW1GwzF4K+wp++xjItzF8xUfc1Ulg92ja2ShRGihH/dNd+EwyOveDjwvb9OXzYlpw5914WAK/CifscREVKtaSj6N35DUfwhomfqjRyU3PR6BI3y67bC3UGqwyJ7RMtMUJ90dwQO9Gb2jNRVF3CkIgT1Ll5ji3u6hIYqGspy+k0FK498rUjhzqCWfH5D5SjIZtZ4n4eeLzVD+vUxB5sRN3Dy1leu9yoppnmuKd+E3ce7fUkcmIbAkczjeilzcQV8rEqcNmRNPTcxRa9WVu6Gxbt3uEzK2zIT98iDf3CmIHO+kdxV+RcmdcHi8PA8andfWjuEtOPhbyB61e1N/1hFUv5zSqe7iHqEkKh/R71FGwoII73d+DKq2U7Damu3pMukdoLlm+al8xdrDhnxOAxL7y7T2DNS4y2PiXjE/2hEH3gnjwm5gYNUKivNbhLuYJ7N4Vi18D4iB4ygaioQUO658XbfH2PvxSBSL7MmYEFJQtDi
  template:
    metadata:
      name: otel-secrets
      namespace: monitoring
      labels:
        app: otel-collector
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/component: telemetry
        app.kubernetes.io/part-of: hire-adda
    type: Opaque
