---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: hire-adda
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDHdixIPgGQx0VJCSigMXwxFnXs79uChdGYU0sqtRV8ewou/oNuBUCqS7FVKONrjwtecjHT/EeUbA9QxCxZoJcSjDqpg9Lh5F0NPGJt9XV3EHt3TK3I9L/OdrhgwU4EDROJs0PSfyFVvWu6Elqcj1taHEHkxelD3Fhxl0RgDO4FQxKvhwwIjHVrFZ49EPSoyQ+ak2cBSurpTpvCt5APpTgL5ZyQ2WZHpovvt0eKZjtaLqvX+KAKKkIW+wCszSXFb8yhelsRNBzLbVj9b+UYXk66uWnJ4dOHtwqi+gRPqE5pZJhyu6gfBcnOoDeZZEwJ8vS5kxZEoqq5vZM4ZhAKKIGR5am6Lv6tJGzhA9fH0HSbokl1d+QEJR5Zuvnjm4C+l4Zrm/53PU8P4FYl3VP0rlApiUMxynKPNxQ1USdtlkiqXuKOS15T8ulbiUR9fu6K8depzjwtp7lhD/uERdX4jKDiSOP8etQSsA6ptpxOss8MfgSZ52K4+7U5riTzymDaYKhMdtO8mVNic8CLpm8A6+UAG5T7v3nOSNAfzp4pxqXQdIdtie/fZpljjVdAgoJ/Tbuq5cLTvVXpSnnJSj5/cL4RFD+mhbQ69ocAsMhBIMqxQaex2QzaRGHO7i+5z2GUfAMatGu42AFS10Ah6cFYKzKgkiY5l+T9fPj6yG4NYA6S3cst4NJuEeNTVCF6+n9+ww5sdAOVXCDLyu8J4dzWS4ZO/Nk6aoCVuvVkFrN6mk4HQNXeetdSZSR9digDrNKg3FofaUb5qbSP5qkcFbeOylzp
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: hire-adda
