# ============================================================
# SealedSecret — Velero R2 Backup Credentials
# ============================================================
# Contains Cloudflare R2 credentials in AWS-format for Velero.
# Regenerate: kubeseal on VPS with --controller-name sealed-secrets-controller
# ============================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
  labels:
    app: velero
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: hire-adda
spec:
  encryptedData:
    cloud: AgAzGTg39PeJ7X163qh14Uyj38YaFp1pymOaTOdhKTCx9KlfHyuDqzpvSomBca6Qkv+abH7/l2WSElG3jLk9aFg98i+wUjnLx1GN5JseHSghLOZePXvBUtVgZ2iT4+81j7ymKIlCWxcl6U+vUtes3mtgunkjgjLhYYsTGFvHoAIMfI2epqzACfx1OJLwohyMTG+MmXwBK8ccS1/mZA2uIKDhQBzg6pHBQzhXjt0gDFDRDaqZGFKm0n2qsPGSO1SnILsuumTNy3jJW0mr2krkpHnGhXA/59ZBQu2Bp768gB2GFHaHRIcZyyFa33W8oIL9s1a7VgN4Bi/RYp9mYebfC0jbfp7dVMUSdwlOB2ICsxJWCKHE1XL7p57hT8oHr6T6DpaPbL2EIgDfn/oIofvcFweAsn5SDR+X8Zy9Zzlj+NiAackQxlTdbWbCrM1tVm8ZfiCNRULY/weBxiX73iA+e9VjyWDgym501YLsYmw7gzYybal370mVhrmbqUAd0mElx8iLEgiX9WzmjeKIrzm2dzgQMrE7OgL9OUt3CbP7Z34MZn4JBuDsI+1iw5SPwqpc5XtNR9/qcstAx2/jrAbcJsVcV6TNP80A4wrOIyU18Rs9U0ysPqWfLLld0YZvwDmMNLexq1goOwWFmdlUHO1WFqgYAj+ckTJyqt1jJGdpv/SG46eYVAXP70ULU5LfSwX6fvJVlA0XUfVJCtOQwosrgQEf1EuoaWXl9kD2MIr2MsrTLyFJ6GOhZcelViYDSdre87eq3jABw1Z901+RK6Bkw6rLw8Pt+ifaTgXV5VvtA0/PoaZWIp+k+u4gbdm5CmXwnOWNOpVkGW3pNKtOvleYj8QnP5PF91EGQgCLlB/hlE7AhY6L8iR38KfFbTpWZxGpMOKOJ80=
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
      labels:
        app: velero
        app.kubernetes.io/name: velero
        app.kubernetes.io/component: backup
        app.kubernetes.io/part-of: hire-adda
    type: Opaque
