/**
 * Backend endpoint paths.
 *
 * Pruned to what this module calls. The host platform carried 488 keys across
 * 24 groups (jobs, candidates, employers, admin, billing, tickets, search,
 * verifications, webhooks, the email system…); 393 of them addressed endpoints
 * that no longer exist on this backend.
 *
 * `SUPER_ADMIN` keeps its name only because 111 call sites spell it that way —
 * there are no roles here, and every route under it is gated by the single app
 * password (see backend/src/middleware/app-password.ts).
 */
export const API = {
  SUPER_ADMIN: {
    WA_CHANNELS: '/whatsapp/channels',
    WA_CONVERSATIONS: '/whatsapp/conversations',
    WA_CONVERSATIONS_BULK: '/whatsapp/conversations/bulk',
    WA_UNREAD_TOTAL: '/whatsapp/unread-total',
    WA_CONVERSATION: (id: string) => `/whatsapp/conversations/${id}`,
    WA_MESSAGES: (id: string) => `/whatsapp/conversations/${id}/messages`,
    WA_MESSAGES_DELETE: (id: string) => `/whatsapp/conversations/${id}/messages/delete`,
    WA_READ: (id: string) => `/whatsapp/conversations/${id}/read`,
    WA_ASSIGN: (id: string) => `/whatsapp/conversations/${id}/assign`,
    WA_STATUS: (id: string) => `/whatsapp/conversations/${id}/status`,
    WA_MEDIA: (id: string) => `/whatsapp/media/${id}`,
    WA_SEND_MEDIA: (id: string) => `/whatsapp/conversations/${id}/media`,
    WA_TEMPLATES: '/whatsapp/templates',
    WA_TEMPLATE: (id: string) => `/whatsapp/templates/${id}`,
    WA_TEMPLATE_SYNC: '/whatsapp/templates/sync',
    WA_TEMPLATE_MEDIA_HANDLE: '/whatsapp/templates/media-handle',
    WA_TEMPLATE_ANALYTICS: (id: string) => `/whatsapp/templates/${id}/analytics`,
    WA_START_CONVERSATION: '/whatsapp/conversations',
    WA_SEND_TEMPLATE: (id: string) => `/whatsapp/conversations/${id}/template`,
    WA_CONTACTS: '/whatsapp/contacts',
    WA_CONTACTS_BULK: '/whatsapp/contacts/bulk',
    WA_CONTACT: (id: string) => `/whatsapp/contacts/${id}`,
    WA_CONTACT_IMPORT: '/whatsapp/contacts/import',
    WA_CAMPAIGNS: '/whatsapp/campaigns',
    WA_CAMPAIGN: (id: string) => `/whatsapp/campaigns/${id}`,
    WA_CAMPAIGN_PREVIEW: (id: string) => `/whatsapp/campaigns/${id}/preview`,
    WA_CAMPAIGN_RECIPIENTS: (id: string) => `/whatsapp/campaigns/${id}/recipients`,
    WA_CAMPAIGN_LAUNCH: (id: string) => `/whatsapp/campaigns/${id}/launch`,
    WA_CAMPAIGN_PAUSE: (id: string) => `/whatsapp/campaigns/${id}/pause`,
    WA_CAMPAIGN_RESUME: (id: string) => `/whatsapp/campaigns/${id}/resume`,
    WA_CAMPAIGN_CANCEL: (id: string) => `/whatsapp/campaigns/${id}/cancel`,
    WA_CAMPAIGN_RETRY: (id: string) => `/whatsapp/campaigns/${id}/retry-failed`,
    WA_CAMPAIGN_DUPLICATE: (id: string) => `/whatsapp/campaigns/${id}/duplicate`,
    WA_CAMPAIGN_TEST_SEND: (id: string) => `/whatsapp/campaigns/${id}/test-send`,
    WA_CAMPAIGN_SAVE_TEMPLATE: (id: string) =>
      `/whatsapp/campaigns/${id}/save-as-template`,
    WA_CAMPAIGN_TEMPLATES: '/whatsapp/campaign-templates',
    WA_CAMPAIGN_TEMPLATE: (id: string) => `/whatsapp/campaign-templates/${id}`,
    WA_CAMPAIGN_TEMPLATE_USE: (id: string) => `/whatsapp/campaign-templates/${id}/use`,
    WA_ANALYTICS: '/whatsapp/analytics',
    WA_ANALYTICS_TIMESERIES: '/whatsapp/analytics/timeseries',
    WA_ANALYTICS_SLA: '/whatsapp/analytics/sla',
    WA_ANALYTICS_AGENTS: '/whatsapp/analytics/agents',
    WA_ANALYTICS_COST: '/whatsapp/analytics/cost',
    WA_ANALYTICS_OPTOUT: '/whatsapp/analytics/optout',
    WA_CANNED_REPLIES: '/whatsapp/canned-replies',
    WA_CANNED_REPLY: (id: string) => `/whatsapp/canned-replies/${id}`,
    WA_FAQS: '/whatsapp/faqs',
    WA_FAQ: (id: string) => `/whatsapp/faqs/${id}`,
    WA_FAQ_REORDER: '/whatsapp/faqs/reorder',
    WA_SEND_INTERACTIVE: (id: string) => `/whatsapp/conversations/${id}/interactive`,
    WA_CHANNEL_SYNC: '/whatsapp/channels/sync',
    WA_CONTACTS_EXPORT: '/whatsapp/contacts/export',
    WA_CAMPAIGN_RECIPIENTS_EXPORT: (id: string) =>
      `/whatsapp/campaigns/${id}/recipients/export`,
    WA_SETTINGS: '/whatsapp/settings',
    // ── Email system (super-admin bulk/marketing) ──
    WA_KEYWORD_RULES: '/whatsapp/keyword-rules',
    WA_KEYWORD_RULE: (id: string) => `/whatsapp/keyword-rules/${id}`,
    WA_NOTES: (id: string) => `/whatsapp/conversations/${id}/notes`,
    WA_NOTE: (id: string, noteId: string) =>
      `/whatsapp/conversations/${id}/notes/${noteId}`,
    WA_LABELS: (id: string) => `/whatsapp/conversations/${id}/labels`,
    WA_SNOOZE: (id: string) => `/whatsapp/conversations/${id}/snooze`,
    WA_CAMPAIGN_STEPS: (id: string) => `/whatsapp/campaigns/${id}/steps`,
    WA_CONTACT_DATA_EXPORT: (id: string) => `/whatsapp/contacts/${id}/export`,
    WA_CONTACT_ERASE: (id: string) => `/whatsapp/contacts/${id}`,
    WA_AGENTS: '/whatsapp/agents',
    // ── P3: A/B variants, short links, transcripts, CSAT, scheduling, advanced analytics ──
    WA_CAMPAIGN_VARIANTS: (id: string) => `/whatsapp/campaigns/${id}/variants`,
    WA_CAMPAIGN_LINKS: (id: string) => `/whatsapp/campaigns/${id}/links`,
    WA_CONV_TRANSCRIPT: (id: string) => `/whatsapp/conversations/${id}/transcript`,
    WA_CONV_CSAT: (id: string) => `/whatsapp/conversations/${id}/csat`,
    WA_CONV_ARCHIVE: (id: string) => `/whatsapp/conversations/${id}/archive`,
    WA_CONV_CLEAR: (id: string) => `/whatsapp/conversations/${id}/clear`,
    WA_CONV_REACTION: (id: string) => `/whatsapp/conversations/${id}/reaction`,
    WA_CONV_LOCATION: (id: string) => `/whatsapp/conversations/${id}/location`,
    WA_CONV_CONTACTS: (id: string) => `/whatsapp/conversations/${id}/contacts`,
    WA_CONV_SCHEDULED: (id: string) => `/whatsapp/conversations/${id}/scheduled`,
    WA_CONV_SCHEDULED_ITEM: (id: string, msgId: string) =>
      `/whatsapp/conversations/${id}/scheduled/${msgId}`,
    WA_ANALYTICS_HEATMAP: '/whatsapp/analytics/heatmap',
    WA_ANALYTICS_KEYWORDS: '/whatsapp/analytics/keywords',
    WA_ANALYTICS_HEALTH_HISTORY: '/whatsapp/analytics/health-history',
    WA_ANALYTICS_CSAT: '/whatsapp/analytics/csat',
    WA_ANALYTICS_META: '/whatsapp/analytics/meta',
    WA_SUPPRESSIONS: '/whatsapp/suppressions',
    WA_SUPPRESSION: (id: string) => `/whatsapp/suppressions/${id}`,
    WA_SEGMENTS: '/whatsapp/segments',
    WA_SEGMENT: (id: string) => `/whatsapp/segments/${id}`,
    WA_CONVERSIONS: '/whatsapp/conversions',
    WA_CAMPAIGN_CONVERSIONS: (id: string) => `/whatsapp/campaigns/${id}/conversions`,
    WA_ANALYTICS_CONVERSIONS: '/whatsapp/analytics/conversions',
  },
} as const;
