export const API = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    UPDATE_PROFILE: '/auth/me/profile',
    UI_PREFERENCES: '/auth/me/ui-preferences',
    REFRESH_TOKEN: '/auth/refresh-token',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_EMAIL_VERIFICATION: '/auth/resend-email-verification',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD_INITIATE: '/auth/change-password/initiate',
    CHANGE_PASSWORD_CONFIRM: '/auth/change-password/confirm',
    LOGOUT_EVERYWHERE: '/auth/logout-everywhere',
    MFA_SETUP: '/auth/mfa/setup',
    MFA_ENABLE: '/auth/mfa/enable',
    MFA_DISABLE: '/auth/mfa/disable',
    MFA_REGENERATE_BACKUP: '/auth/mfa/backup-codes',
    MFA_BACKUP_CODE_COUNT: '/auth/mfa/backup-codes/count',
    MFA_RECOVERY_REQUEST: '/auth/mfa/recovery/request',
    MFA_RECOVERY_VERIFY: '/auth/mfa/recovery/verify',
    VERIFY_MOBILE: '/auth/verify-mobile',
    RESEND_MOBILE_OTP: '/auth/resend-mobile-otp',
    VERIFY_WHATSAPP: '/auth/verify-whatsapp',
    VERIFY_WHATSAPP_OTP: '/auth/verify-whatsapp-otp',
    CHANGE_WHATSAPP_NUMBER: '/auth/change-whatsapp-number',
    REMOVE_WHATSAPP_NUMBER: '/auth/whatsapp-number',
    CHANGE_EMAIL_INITIATE: '/auth/change-email/initiate',
    CHANGE_EMAIL_CONFIRM: '/auth/change-email/confirm',
    CHANGE_EMAIL_RESEND_OTP: '/auth/change-email/resend-otp',
    CHANGE_MOBILE_INITIATE: '/auth/change-mobile/initiate',
    CHANGE_MOBILE_CONFIRM: '/auth/change-mobile/confirm',
    CHANGE_MOBILE_RESEND_OTP: '/auth/change-mobile/resend-otp',
    FIREBASE_LOGIN: '/auth/firebase-login',
    GOOGLE: '/auth/google',
    LINKEDIN: '/auth/linkedin',
    DATA_EXPORT: '/auth/me/data-export',
  },
  WHATSAPP: {
    // User-facing self-serve WhatsApp marketing opt-in (NOT super-admin gated)
    OPTIN: '/whatsapp-optin',
  },
  CANDIDATES: {
    ME: '/candidates/me',
    DASHBOARD: '/candidates/me/dashboard',
    COMPLETENESS: '/candidates/me/completeness',
    RESUME: '/candidates/me/resume',
    RESUME_GENERATE: '/candidates/me/resume/generate',
    RESUME_READINESS: '/candidates/me/resume/readiness',
    RESUME_TEMPLATES: '/candidates/me/resume/templates',
    RESUME_USE_GENERATED: '/candidates/me/resume/use-generated',
    AVATAR: '/candidates/me/avatar',
    PROFILE_VIEWS: '/candidates/me/profile-views',
    BOOST: '/candidates/me/boost',
    BOOST_ACTIVATE: '/candidates/me/boost/activate',
    SEARCH: '/candidates',
    DETAIL: (id: string) => `/candidates/${id}`,
    RESUME_DOWNLOAD: (id: string) => `/candidates/${id}/resume`,
  },
  EMPLOYERS: {
    DASHBOARD: '/employers/dashboard',
    ME: '/employers/me',
    LOGO: '/employers/me/logo',
    COVER_IMAGE: '/employers/me/cover-image',
    PROFILE_VIEWS: '/employers/me/profile-views',
    ENGAGEMENT_METRICS: '/employers/engagement-metrics',
    COMPLETENESS: '/employers/me/completeness',
    ANALYTICS: '/employers/analytics',
    ANALYTICS_EXPORT: '/employers/analytics/export',
    SEARCH_CANDIDATES: '/employers/candidates/search',
    SAVE_CANDIDATE: (id: string) => `/saved-candidates/${id}/toggle`, // Matches saved-candidate.routes.ts
    SAVED_CANDIDATES: '/saved-candidates', // Matches saved-candidate.routes.ts
    SAVED_CANDIDATE_NOTES: (id: string) => `/saved-candidates/${id}/notes`,
    SHORTLIST_CANDIDATE: (candidateId: string) => `/employers/candidates/${candidateId}/shortlist`,
    SELECT_CANDIDATE: (candidateId: string) => `/employers/candidates/${candidateId}/select`,
    BULK_EXPORT_CANDIDATES: '/employers/candidates/bulk-export',
    BULK_EXPORT_RESUMES: '/employers/candidates/bulk-export-resumes',
    CANDIDATE_MATCH_SCORE: (candidateId: string, jobId: string) =>
      `/employers/candidates/${candidateId}/match/${jobId}`,
    SIMILAR_CANDIDATES: (candidateId: string) => `/employers/candidates/${candidateId}/similar`,
    APPLICATIONS: '/employers/applications',
    PUBLIC_PROFILE: (id: string) => `/employers/${id}/public`,
  },
  JOBS: {
    SEARCH: '/jobs',
    DETAIL: (id: string) => `/jobs/${id}`,
    CREATE: '/jobs',
    UPDATE: (id: string) => `/jobs/${id}`,
    DEACTIVATE: (id: string) => `/jobs/${id}/deactivate`,
    OFFLINE_HIRES: (id: string) => `/jobs/${id}/offline-hires`,
    APPLY: (id: string) => `/jobs/${id}/apply`,
    SAVE: (id: string) => `/jobs/${id}/save`,
    SAVED: '/jobs/saved',
    APPLIED: '/jobs/applications/me',
    MY_JOBS: '/jobs/employer/my-jobs',
    APPLICATIONS: (jobId: string) => `/jobs/${jobId}/applications`,
    UPDATE_APPLICATION: (applicationId: string) => `/jobs/applications/${applicationId}`,
    APPLICATION_DETAIL: (applicationId: string) => `/jobs/applications/${applicationId}`,
    WITHDRAW_APPLICATION: (applicationId: string) => `/jobs/applications/${applicationId}/withdraw`,
    CLONE: (id: string) => `/jobs/${id}/clone`,
  },
  JOB_TEMPLATES: {
    LIST: '/employers/job-templates',
    CREATE: '/employers/job-templates',
    UPDATE: (id: string) => `/employers/job-templates/${id}`,
    DELETE: (id: string) => `/employers/job-templates/${id}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    UNREAD_COUNT: '/notifications/unread-count',
  },
  SESSIONS: {
    LIST: '/sessions',
    REVOKE: (id: string) => `/sessions/${id}`,
    REVOKE_ALL: '/sessions',
  },
  DRAFTS: {
    SAVE: '/drafts',
    LIST: '/drafts',
    DETAIL: (id: string) => `/drafts/${id}`,
    DELETE: (id: string) => `/drafts/${id}`,
  },
  ADMIN: {
    STATS: '/admin/stats',
    COMPREHENSIVE_STATS: '/admin/stats/comprehensive',
    ACTIVITY: '/admin/activity',
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    DELETE_USER: (id: string) => `/admin/users/${id}`,
    SUSPEND_USER: (id: string) => `/admin/users/${id}/suspend`,
    ACTIVATE_USER: (id: string) => `/admin/users/${id}/activate`,
    UPDATE_USER_ROLE: (id: string) => `/admin/users/${id}/role`,
    MODERATE_JOB: (id: string) => `/admin/jobs/${id}/status`,
    FLAG_JOB: (id: string) => `/admin/jobs/${id}/flag`,
    ANALYTICS: '/admin/analytics',
    AUDIT_LOGS: '/admin/audit-logs',
    EMAIL_TEMPLATES: '/admin/email-templates',
    EMAIL_TEMPLATES_PREVIEW: '/admin/email-templates/preview',
    EMAIL_TEMPLATES_TEST: '/admin/email-templates/test',
    KAFKA_EVENTS: '/admin/kafka-events',
    KAFKA_DLQ: '/admin/kafka-dlq',
    KAFKA_DLQ_REPLAY: (id: string) => `/admin/kafka-dlq/${id}/replay`,
    KAFKA_REPLAY: '/admin/kafka-replay',
    LIVE_COUNTERS: '/admin/live-counters',
    ONLINE_STATS: '/admin/online-stats',
    TRENDING: '/admin/trending',
    DAILY_ACTIVE_USERS: '/admin/stats/daily-active-users',
    MODERATION_KEYWORDS: '/admin/moderation/keywords',
    MODERATION_KEYWORD_DELETE: (keyword: string) =>
      `/admin/moderation/keywords/${encodeURIComponent(keyword)}`,
    JOBS: '/admin/jobs',
    DELETE_JOB: (id: string) => `/admin/jobs/${id}`,
    APPLICATIONS: '/admin/applications',
    APPLICATION_STATS: '/admin/applications/stats',
    EXPORT_JOBS: '/admin/export-jobs',
    CANCEL_EXPORT_JOB: (jobId: string) => `/admin/export-jobs/${jobId}`,
    REPORTS: {
      USERS: '/reports/users/export',
      JOBS: '/reports/jobs/export',
      ANALYTICS: '/reports/analytics/export',
    },
  },
  SUPER_ADMIN: {
    CREATE_ADMIN: '/super-admin/admins',
    LIST_ADMINS: '/super-admin/admins',
    REMOVE_ADMIN: (id: string) => `/super-admin/admins/${id}`,
    // Resume Watermark Toolkit
    RESUME_WM_CONFIG: '/super-admin/resume-watermark/config',
    RESUME_WM_ON_PLATFORM: '/super-admin/resume-watermark/on-platform',
    RESUME_WM_ON_PLATFORM_DOWNLOAD: (id: string) =>
      `/super-admin/resume-watermark/on-platform/${id}/download`,
    RESUME_WM_ON_PLATFORM_BULK_DOWNLOAD: '/super-admin/resume-watermark/on-platform/bulk-download',
    RESUME_WM_OFF_PLATFORM: '/super-admin/resume-watermark/off-platform',
    RESUME_WM_OFF_PLATFORM_ONE: (id: string) => `/super-admin/resume-watermark/off-platform/${id}`,
    RESUME_WM_OFF_PLATFORM_RESUMES: (id: string) =>
      `/super-admin/resume-watermark/off-platform/${id}/resumes`,
    RESUME_WM_OFF_PLATFORM_RESUME: (id: string, resumeId: string) =>
      `/super-admin/resume-watermark/off-platform/${id}/resumes/${resumeId}`,
    RESUME_WM_OFF_PLATFORM_RESUME_DOWNLOAD: (id: string, resumeId: string) =>
      `/super-admin/resume-watermark/off-platform/${id}/resumes/${resumeId}/download`,
    RESUME_WM_OFF_PLATFORM_BULK_DELETE: '/super-admin/resume-watermark/off-platform/bulk-delete',
    RESUME_WM_OFF_PLATFORM_BULK_DOWNLOAD:
      '/super-admin/resume-watermark/off-platform/bulk-download',
    GET_CONFIG: '/super-admin/config',
    UPDATE_CONFIG: '/super-admin/config',
    CREATE_USER: '/super-admin/users',
    UPDATE_USER_PROFILE: (id: string) => `/super-admin/users/${id}/profile`,
    SEND_PASSWORD_RESET_OTP: (id: string) => `/super-admin/users/${id}/password-otp`,
    RESET_USER_PASSWORD: (id: string) => `/super-admin/users/${id}/password`,
    DEACTIVATE_USER: (id: string) => `/super-admin/users/${id}/deactivate`,
    UPLOAD_USER_AVATAR: (id: string) => `/super-admin/users/${id}/avatar`,
    REMOVE_USER_AVATAR: (id: string) => `/super-admin/users/${id}/avatar`,
    USER_SESSIONS: (id: string) => `/super-admin/users/${id}/sessions`,
    REVOKE_USER_SESSIONS: (id: string) => `/super-admin/users/${id}/sessions`,
    MFA_SETUP: (id: string) => `/super-admin/users/${id}/mfa/setup`,
    MFA_ENABLE: (id: string) => `/super-admin/users/${id}/mfa/enable`,
    MFA_DISABLE: (id: string) => `/super-admin/users/${id}/mfa/disable`,
    MFA_STATUS: (id: string) => `/super-admin/users/${id}/mfa/status`,
    MFA_REGEN_BACKUP: (id: string) => `/super-admin/users/${id}/mfa/backup-codes`,
    REVOKE_USER_SESSION: (userId: string, sessionId: string) =>
      `/super-admin/users/${userId}/sessions/${sessionId}`,
    // Admin email / mobile / WhatsApp managed verification
    ADMIN_EMAIL_INITIATE: (id: string) => `/super-admin/users/${id}/email/initiate`,
    ADMIN_EMAIL_CONFIRM: (id: string) => `/super-admin/users/${id}/email/confirm`,
    ADMIN_EMAIL_RESEND: (id: string) => `/super-admin/users/${id}/email/resend`,
    ADMIN_MOBILE_INITIATE: (id: string) => `/super-admin/users/${id}/mobile/initiate`,
    ADMIN_MOBILE_CONFIRM: (id: string) => `/super-admin/users/${id}/mobile/confirm`,
    ADMIN_MOBILE_RESEND: (id: string) => `/super-admin/users/${id}/mobile/resend`,
    REMOVE_ADMIN_MOBILE: (id: string) => `/super-admin/users/${id}/mobile`,
    ADMIN_WHATSAPP_VERIFY: (id: string) => `/super-admin/users/${id}/whatsapp/verify`,
    ADMIN_WHATSAPP_CHANGE: (id: string) => `/super-admin/users/${id}/whatsapp/change`,
    ADMIN_WHATSAPP_CONFIRM: (id: string) => `/super-admin/users/${id}/whatsapp/confirm`,
    REMOVE_ADMIN_WHATSAPP: (id: string) => `/super-admin/users/${id}/whatsapp`,
    // Admin password managed change
    ADMIN_PASSWORD_INITIATE: (id: string) => `/super-admin/users/${id}/password/initiate`,
    ADMIN_PASSWORD_CONFIRM: (id: string) => `/super-admin/users/${id}/password/confirm`,
    ADMIN_PASSWORD_RESEND: (id: string) => `/super-admin/users/${id}/password/resend`,
    // Job posting on behalf of a company (admin override)
    JOBS_COMPANIES: '/super-admin/companies',
    JOBS_CREATE: '/super-admin/jobs',
    JOB_GET: (id: string) => `/super-admin/jobs/${id}`,
    JOB_UPDATE: (id: string) => `/super-admin/jobs/${id}`,
    // WhatsApp inbox
    WA_CHANNELS: '/whatsapp/channels',
    WA_CONVERSATIONS: '/whatsapp/conversations',
    WA_CONVERSATIONS_BULK: '/whatsapp/conversations/bulk',
    WA_UNREAD_TOTAL: '/whatsapp/unread-total',
    WA_CONVERSATION: (id: string) => `/whatsapp/conversations/${id}`,
    WA_MESSAGES: (id: string) => `/whatsapp/conversations/${id}/messages`,
    WA_MESSAGES_DELETE: (id: string) => `/whatsapp/conversations/${id}/messages/delete`,
    WA_READ: (id: string) => `/whatsapp/conversations/${id}/read`,
    WA_ASSIGN: (id: string) => `/whatsapp/conversations/${id}/assign`,
    WA_STATUS: (id: string) => `/whatsapp/conversations/${id}/status`,
    WA_MEDIA: (id: string) => `/whatsapp/media/${id}`,
    WA_SEND_MEDIA: (id: string) => `/whatsapp/conversations/${id}/media`,
    WA_TEMPLATES: '/whatsapp/templates',
    WA_TEMPLATE: (id: string) => `/whatsapp/templates/${id}`,
    WA_TEMPLATE_SYNC: '/whatsapp/templates/sync',
    WA_TEMPLATE_MEDIA_HANDLE: '/whatsapp/templates/media-handle',
    WA_TEMPLATE_ANALYTICS: (id: string) => `/whatsapp/templates/${id}/analytics`,
    WA_START_CONVERSATION: '/whatsapp/conversations',
    WA_SEND_TEMPLATE: (id: string) => `/whatsapp/conversations/${id}/template`,
    WA_CONTACTS: '/whatsapp/contacts',
    WA_CONTACTS_BULK: '/whatsapp/contacts/bulk',
    WA_CONTACT: (id: string) => `/whatsapp/contacts/${id}`,
    WA_CONTACT_IMPORT: '/whatsapp/contacts/import',
    WA_PLATFORM_USERS: '/whatsapp/contacts/platform-users',
    WA_CAMPAIGNS: '/whatsapp/campaigns',
    WA_CAMPAIGN: (id: string) => `/whatsapp/campaigns/${id}`,
    WA_CAMPAIGN_PREVIEW: (id: string) => `/whatsapp/campaigns/${id}/preview`,
    WA_CAMPAIGN_RECIPIENTS: (id: string) => `/whatsapp/campaigns/${id}/recipients`,
    WA_CAMPAIGN_LAUNCH: (id: string) => `/whatsapp/campaigns/${id}/launch`,
    WA_CAMPAIGN_PAUSE: (id: string) => `/whatsapp/campaigns/${id}/pause`,
    WA_CAMPAIGN_RESUME: (id: string) => `/whatsapp/campaigns/${id}/resume`,
    WA_CAMPAIGN_CANCEL: (id: string) => `/whatsapp/campaigns/${id}/cancel`,
    WA_CAMPAIGN_RETRY: (id: string) => `/whatsapp/campaigns/${id}/retry-failed`,
    WA_CAMPAIGN_DUPLICATE: (id: string) => `/whatsapp/campaigns/${id}/duplicate`,
    WA_CAMPAIGN_TEST_SEND: (id: string) => `/whatsapp/campaigns/${id}/test-send`,
    WA_CAMPAIGN_SAVE_TEMPLATE: (id: string) =>
      `/whatsapp/campaigns/${id}/save-as-template`,
    WA_CAMPAIGN_TEMPLATES: '/whatsapp/campaign-templates',
    WA_CAMPAIGN_TEMPLATE: (id: string) => `/whatsapp/campaign-templates/${id}`,
    WA_CAMPAIGN_TEMPLATE_USE: (id: string) => `/whatsapp/campaign-templates/${id}/use`,
    WA_ANALYTICS: '/whatsapp/analytics',
    WA_ANALYTICS_TIMESERIES: '/whatsapp/analytics/timeseries',
    WA_ANALYTICS_SLA: '/whatsapp/analytics/sla',
    WA_ANALYTICS_AGENTS: '/whatsapp/analytics/agents',
    WA_ANALYTICS_COST: '/whatsapp/analytics/cost',
    WA_ANALYTICS_OPTOUT: '/whatsapp/analytics/optout',
    WA_CANNED_REPLIES: '/whatsapp/canned-replies',
    WA_CANNED_REPLY: (id: string) => `/whatsapp/canned-replies/${id}`,
    WA_FAQS: '/whatsapp/faqs',
    WA_FAQ: (id: string) => `/whatsapp/faqs/${id}`,
    WA_FAQ_REORDER: '/whatsapp/faqs/reorder',
    WA_SEND_INTERACTIVE: (id: string) => `/whatsapp/conversations/${id}/interactive`,
    WA_CHANNEL_SYNC: '/whatsapp/channels/sync',
    WA_CONTACTS_EXPORT: '/whatsapp/contacts/export',
    WA_CAMPAIGN_RECIPIENTS_EXPORT: (id: string) =>
      `/whatsapp/campaigns/${id}/recipients/export`,
    WA_SETTINGS: '/whatsapp/settings',
    // ── Email system (super-admin bulk/marketing) ──
    EMAIL_SENDERS: '/super-admin/email/senders',
    EMAIL_SENDER: (id: string) => `/super-admin/email/senders/${id}`,
    EMAIL_SENDER_VERIFY: (id: string) => `/super-admin/email/senders/${id}/verify`,
    EMAIL_TEMPLATES_L: '/super-admin/email/templates',
    EMAIL_TEMPLATE: (id: string) => `/super-admin/email/templates/${id}`,
    EMAIL_TEMPLATE_PREVIEW: '/super-admin/email/templates/preview',
    EMAIL_TEMPLATE_TEST: '/super-admin/email/templates/test',
    EMAIL_TEMPLATES_BULK_DELETE: '/super-admin/email/templates/bulk-delete',
    EMAIL_TEMPLATES_BULK_STATUS: '/super-admin/email/templates/bulk-status',
    EMAIL_TEMPLATES_BULK_DUPLICATE: '/super-admin/email/templates/bulk-duplicate',
    EMAIL_CAMPAIGNS: '/super-admin/email/campaigns',
    EMAIL_CAMPAIGNS_BULK: '/super-admin/email/campaigns/bulk',
    EMAIL_CAMPAIGN: (id: string) => `/super-admin/email/campaigns/${id}`,
    EMAIL_CAMPAIGN_ARCHIVE: (id: string) => `/super-admin/email/campaigns/${id}/archive`,
    EMAIL_CAMPAIGN_LAUNCH: (id: string) => `/super-admin/email/campaigns/${id}/launch`,
    EMAIL_CAMPAIGN_PAUSE: (id: string) => `/super-admin/email/campaigns/${id}/pause`,
    EMAIL_CAMPAIGN_RESUME: (id: string) => `/super-admin/email/campaigns/${id}/resume`,
    EMAIL_CAMPAIGN_CANCEL: (id: string) => `/super-admin/email/campaigns/${id}/cancel`,
    EMAIL_CAMPAIGN_RETRY: (id: string) => `/super-admin/email/campaigns/${id}/retry-failed`,
    EMAIL_CAMPAIGN_DUPLICATE: (id: string) => `/super-admin/email/campaigns/${id}/duplicate`,
    EMAIL_CAMPAIGN_AUDIENCE: (id: string) => `/super-admin/email/campaigns/${id}/audience`,
    EMAIL_CAMPAIGN_VARIANTS: (id: string) => `/super-admin/email/campaigns/${id}/variants`,
    EMAIL_CAMPAIGN_STEPS: (id: string) => `/super-admin/email/campaigns/${id}/steps`,
    EMAIL_CAMPAIGN_RECIPIENTS: (id: string) => `/super-admin/email/campaigns/${id}/recipients`,
    EMAIL_CAMPAIGN_RECIPIENTS_EXPORT: (id: string) =>
      `/super-admin/email/campaigns/${id}/recipients/export`,
    EMAIL_CAMPAIGN_TEST_SEND: (id: string) => `/super-admin/email/campaigns/${id}/test-send`,
    EMAIL_CAMPAIGN_SAVE_TEMPLATE: (id: string) =>
      `/super-admin/email/campaigns/${id}/save-as-template`,
    EMAIL_CAMPAIGN_ANALYTICS: (id: string) => `/super-admin/email/campaigns/${id}/analytics`,
    EMAIL_BLUEPRINTS: '/super-admin/email/campaign-templates',
    EMAIL_BLUEPRINT: (id: string) => `/super-admin/email/campaign-templates/${id}`,
    EMAIL_BLUEPRINT_USE: (id: string) => `/super-admin/email/campaign-templates/${id}/use`,
    EMAIL_CONTACTS_L: '/super-admin/email/contacts',
    EMAIL_CONTACT: (id: string) => `/super-admin/email/contacts/${id}`,
    EMAIL_CONTACT_BLOCK: (id: string) => `/super-admin/email/contacts/${id}/block`,
    EMAIL_CONTACT_ERASE: (id: string) => `/super-admin/email/contacts/${id}/erase`,
    EMAIL_CONTACTS_IMPORT: '/super-admin/email/contacts/import',
    EMAIL_CONTACTS_IMPORT_ROWS: '/super-admin/email/contacts/import-rows',
    EMAIL_CONTACTS_EXPORT: '/super-admin/email/contacts/export',
    EMAIL_CONTACTS_BULK_TAG: '/super-admin/email/contacts/bulk-tag',
    EMAIL_CONTACTS_BULK_UPDATE: '/super-admin/email/contacts/bulk-update',
    EMAIL_CONTACTS_BULK_DELETE: '/super-admin/email/contacts/bulk-delete',
    EMAIL_PLATFORM_USERS: '/super-admin/email/platform-users',
    EMAIL_PLATFORM_USERS_COUNT: '/super-admin/email/platform-users/count',
    EMAIL_PLATFORM_USERS_SYNC: '/super-admin/email/platform-users/sync',
    EMAIL_PLATFORM_USERS_EXPORT: '/super-admin/email/platform-users/export',
    EMAIL_SEGMENTS: '/super-admin/email/segments',
    EMAIL_SEGMENT: (id: string) => `/super-admin/email/segments/${id}`,
    EMAIL_SETS: '/super-admin/email/sets',
    EMAIL_SET: (id: string) => `/super-admin/email/sets/${id}`,
    EMAIL_SET_MEMBERS: (id: string) => `/super-admin/email/sets/${id}/members`,
    EMAIL_SET_AUDIENCE: (id: string) => `/super-admin/email/sets/${id}/audience`,
    EMAIL_SET_EXPORT: (id: string) => `/super-admin/email/sets/${id}/export`,
    EMAIL_SETS_BULK_DELETE: '/super-admin/email/sets/bulk-delete',
    EMAIL_SEGMENT_SIZE: (id: string) => `/super-admin/email/segments/${id}/size`,
    EMAIL_SUPPRESSIONS: '/super-admin/email/suppressions',
    EMAIL_SUPPRESSIONS_EXPORT: '/super-admin/email/suppressions/export',
    EMAIL_SUPPRESSIONS_IMPORT: '/super-admin/email/suppressions/import',
    EMAIL_SUPPRESSIONS_BULK_DELETE: '/super-admin/email/suppressions/bulk-delete',
    EMAIL_SUPPRESSION: (id: string) => `/super-admin/email/suppressions/${id}`,
    EMAIL_SCHEDULED_LIST: '/super-admin/email/scheduled',
    EMAIL_UNSUBSCRIBES: '/super-admin/email/unsubscribes',
    EMAIL_UNSUBSCRIBES_EXPORT: '/super-admin/email/unsubscribes/export',
    EMAIL_UNSUBSCRIBES_RESUBSCRIBE: '/super-admin/email/unsubscribes/bulk-resubscribe',
    EMAIL_UNSUBSCRIBES_BULK_DELETE: '/super-admin/email/unsubscribes/bulk-delete',
    EMAIL_ANALYTICS_OVERVIEW: '/super-admin/email/analytics/overview',
    EMAIL_ANALYTICS_TIMESERIES: '/super-admin/email/analytics/timeseries',
    EMAIL_ANALYTICS_DELIVERABILITY: '/super-admin/email/analytics/deliverability',
    EMAIL_ANALYTICS_HEATMAP: '/super-admin/email/analytics/heatmap',
    EMAIL_ANALYTICS_TOP_LINKS: '/super-admin/email/analytics/top-links',
    EMAIL_BULK_JOBS: '/super-admin/email/bulk-jobs',
    EMAIL_BULK_JOB: (id: string) => `/super-admin/email/bulk-jobs/${id}`,
    EMAIL_BULK_UNDO: (id: string) => `/super-admin/email/undo/${id}`,
    EMAIL_SETTINGS: '/super-admin/email/settings',
    EMAIL_THREADS: '/super-admin/email/threads',
    EMAIL_THREADS_UNREAD: '/super-admin/email/threads/unread-count',
    EMAIL_THREADS_BULK: '/super-admin/email/threads/bulk',
    EMAIL_THREAD: (id: string) => `/super-admin/email/threads/${id}`,
    EMAIL_THREAD_READ: (id: string) => `/super-admin/email/threads/${id}/read`,
    EMAIL_THREAD_ASSIGN: (id: string) => `/super-admin/email/threads/${id}/assign`,
    EMAIL_THREAD_STATUS: (id: string) => `/super-admin/email/threads/${id}/status`,
    EMAIL_THREAD_LABELS: (id: string) => `/super-admin/email/threads/${id}/labels`,
    EMAIL_THREAD_SNOOZE: (id: string) => `/super-admin/email/threads/${id}/snooze`,
    EMAIL_THREAD_ARCHIVE: (id: string) => `/super-admin/email/threads/${id}/archive`,
    EMAIL_THREAD_NOTES: (id: string) => `/super-admin/email/threads/${id}/notes`,
    EMAIL_THREAD_REPLY: (id: string) => `/super-admin/email/threads/${id}/reply`,
    EMAIL_THREAD_SCHEDULE: (id: string) => `/super-admin/email/threads/${id}/schedule`,
    EMAIL_SCHEDULED: (id: string) => `/super-admin/email/scheduled/${id}`,
    EMAIL_CANNED_REPLIES: '/super-admin/email/canned-replies',
    EMAIL_CANNED_REPLY: (id: string) => `/super-admin/email/canned-replies/${id}`,
    EMAIL_RULES: '/super-admin/email/rules',
    EMAIL_RULE: (id: string) => `/super-admin/email/rules/${id}`,
    // ── Email: template builder extras, snippets, assets, contact detail, analytics drill-downs ──
    EMAIL_TEMPLATE_DUPLICATE: (id: string) => `/super-admin/email/templates/${id}/duplicate`,
    EMAIL_TEMPLATE_VERSIONS: (id: string) => `/super-admin/email/templates/${id}/versions`,
    EMAIL_TEMPLATE_RESTORE: (id: string) => `/super-admin/email/templates/${id}/restore`,
    EMAIL_TEMPLATE_LINT: '/super-admin/email/templates/lint',
    EMAIL_TEMPLATE_PLAINTEXT: '/super-admin/email/templates/plain-text',
    EMAIL_SNIPPETS: '/super-admin/email/snippets',
    EMAIL_SNIPPET: (id: string) => `/super-admin/email/snippets/${id}`,
    EMAIL_ASSETS: '/super-admin/email/assets',
    EMAIL_ATTACHMENTS: '/super-admin/email/attachments',
    EMAIL_CONTACT_TIMELINE: (id: string) => `/super-admin/email/contacts/${id}/timeline`,
    EMAIL_CONTACT_DATA_EXPORT: (id: string) => `/super-admin/email/contacts/${id}/data-export`,
    EMAIL_CAMPAIGN_STOP_RECURRENCE: (id: string) =>
      `/super-admin/email/campaigns/${id}/stop-recurrence`,
    EMAIL_CAMPAIGN_MATERIALIZE: (id: string) => `/super-admin/email/campaigns/${id}/materialize`,
    EMAIL_CAMPAIGN_RECONCILE: (id: string) => `/super-admin/email/campaigns/${id}/reconcile`,
    EMAIL_ANALYTICS_BOUNCES: '/super-admin/email/analytics/bounces',
    EMAIL_ANALYTICS_EVENTS: '/super-admin/email/analytics/events',
    EMAIL_ANALYTICS_COMPARE: '/super-admin/email/analytics/compare',
    EMAIL_ANALYTICS_EXPORT: '/super-admin/email/analytics/export',
    EMAIL_ANALYTICS_CLIENTS: '/super-admin/email/analytics/clients',
    EMAIL_ANALYTICS_DOMAINS: '/super-admin/email/analytics/domains',
    EMAIL_ANALYTICS_LEADERBOARD: '/super-admin/email/analytics/leaderboard',
    EMAIL_ANALYTICS_LIST_GROWTH: '/super-admin/email/analytics/list-growth',
    EMAIL_ANALYTICS_BOUNCE_REASONS: '/super-admin/email/analytics/bounce-reasons',
    // One-on-one mailbox (webmail)
    EMAIL_MAIL_ACCOUNTS: '/super-admin/email/mailbox/accounts',
    EMAIL_MAIL_ACCOUNT: (id: string) => `/super-admin/email/mailbox/accounts/${id}`,
    EMAIL_MAIL_ACCOUNT_TEST: '/super-admin/email/mailbox/accounts/test',
    EMAIL_MAIL_ACCOUNT_TEST_ID: (id: string) => `/super-admin/email/mailbox/accounts/${id}/test`,
    EMAIL_MAIL_FOLDERS: (id: string) => `/super-admin/email/mailbox/accounts/${id}/folders`,
    EMAIL_MAIL_SPECIAL: (id: string) => `/super-admin/email/mailbox/accounts/${id}/special`,
    EMAIL_MAIL_MESSAGES: (id: string) => `/super-admin/email/mailbox/accounts/${id}/messages`,
    EMAIL_MAIL_THREADS: (id: string) => `/super-admin/email/mailbox/accounts/${id}/threads`,
    EMAIL_MAIL_THREAD: (id: string) => `/super-admin/email/mailbox/accounts/${id}/thread`,
    EMAIL_MAIL_SUGGEST: (id: string) => `/super-admin/email/mailbox/accounts/${id}/suggest`,
    EMAIL_MAIL_FORWARD_ATTACH: (id: string) =>
      `/super-admin/email/mailbox/accounts/${id}/forward-attachments`,
    EMAIL_MAIL_MESSAGE: (id: string) => `/super-admin/email/mailbox/accounts/${id}/message`,
    EMAIL_MAIL_ATTACHMENT: (id: string) => `/super-admin/email/mailbox/accounts/${id}/attachment`,
    EMAIL_MAIL_RAW: (id: string) => `/super-admin/email/mailbox/accounts/${id}/raw`,
    EMAIL_MAIL_FLAGS: (id: string) => `/super-admin/email/mailbox/accounts/${id}/flags`,
    EMAIL_MAIL_MOVE: (id: string) => `/super-admin/email/mailbox/accounts/${id}/move`,
    EMAIL_MAIL_COPY: (id: string) => `/super-admin/email/mailbox/accounts/${id}/copy`,
    EMAIL_MAIL_DELETE: (id: string) => `/super-admin/email/mailbox/accounts/${id}/delete`,
    EMAIL_MAIL_SEND: (id: string) => `/super-admin/email/mailbox/accounts/${id}/send`,
    EMAIL_MAIL_DRAFT: (id: string) => `/super-admin/email/mailbox/accounts/${id}/draft`,
    EMAIL_MAIL_UPLOAD: (id: string) => `/super-admin/email/mailbox/accounts/${id}/attachments`,
    WA_KEYWORD_RULES: '/whatsapp/keyword-rules',
    WA_KEYWORD_RULE: (id: string) => `/whatsapp/keyword-rules/${id}`,
    WA_NOTES: (id: string) => `/whatsapp/conversations/${id}/notes`,
    WA_NOTE: (id: string, noteId: string) =>
      `/whatsapp/conversations/${id}/notes/${noteId}`,
    WA_LABELS: (id: string) => `/whatsapp/conversations/${id}/labels`,
    WA_SNOOZE: (id: string) => `/whatsapp/conversations/${id}/snooze`,
    WA_CAMPAIGN_STEPS: (id: string) => `/whatsapp/campaigns/${id}/steps`,
    WA_CONTACT_DATA_EXPORT: (id: string) => `/whatsapp/contacts/${id}/export`,
    WA_CONTACT_ERASE: (id: string) => `/whatsapp/contacts/${id}`,
    WA_AGENTS: '/whatsapp/agents',
    // ── P3: A/B variants, short links, transcripts, CSAT, scheduling, advanced analytics ──
    WA_CAMPAIGN_VARIANTS: (id: string) => `/whatsapp/campaigns/${id}/variants`,
    WA_CAMPAIGN_LINKS: (id: string) => `/whatsapp/campaigns/${id}/links`,
    WA_CONV_TRANSCRIPT: (id: string) => `/whatsapp/conversations/${id}/transcript`,
    WA_CONV_CSAT: (id: string) => `/whatsapp/conversations/${id}/csat`,
    WA_CONV_ARCHIVE: (id: string) => `/whatsapp/conversations/${id}/archive`,
    WA_CONV_CLEAR: (id: string) => `/whatsapp/conversations/${id}/clear`,
    WA_CONV_REACTION: (id: string) => `/whatsapp/conversations/${id}/reaction`,
    WA_CONV_LOCATION: (id: string) => `/whatsapp/conversations/${id}/location`,
    WA_CONV_CONTACTS: (id: string) => `/whatsapp/conversations/${id}/contacts`,
    WA_CONV_SCHEDULED: (id: string) => `/whatsapp/conversations/${id}/scheduled`,
    WA_CONV_SCHEDULED_ITEM: (id: string, msgId: string) =>
      `/whatsapp/conversations/${id}/scheduled/${msgId}`,
    WA_ANALYTICS_HEATMAP: '/whatsapp/analytics/heatmap',
    WA_ANALYTICS_KEYWORDS: '/whatsapp/analytics/keywords',
    WA_ANALYTICS_HEALTH_HISTORY: '/whatsapp/analytics/health-history',
    WA_ANALYTICS_CSAT: '/whatsapp/analytics/csat',
    WA_ANALYTICS_META: '/whatsapp/analytics/meta',
    WA_SUPPRESSIONS: '/whatsapp/suppressions',
    WA_SUPPRESSION: (id: string) => `/whatsapp/suppressions/${id}`,
    WA_SEGMENTS: '/whatsapp/segments',
    WA_SEGMENT: (id: string) => `/whatsapp/segments/${id}`,
    WA_CONVERSIONS: '/whatsapp/conversions',
    WA_CAMPAIGN_CONVERSIONS: (id: string) => `/whatsapp/campaigns/${id}/conversions`,
    WA_ANALYTICS_CONVERSIONS: '/whatsapp/analytics/conversions',
    WA_PLATFORM_CONTEXT: (id: string) => `/whatsapp/contacts/${id}/platform-context`,
  },
  DEVICES: {
    FCM: '/devices/fcm',
    FCM_DELETE: (tokenId: string) => `/devices/fcm/${tokenId}`,
    PUSH_SUBSCRIPTIONS: '/devices/push-subscriptions',
    PUSH_SUBSCRIPTION_DELETE: (id: string) => `/devices/push-subscriptions/${id}`,
  },
  VERIFICATIONS: {
    REQUEST: '/verifications/request',
    MINE: '/verifications/mine',
    PENDING: '/verifications/pending',
    ALL: '/verifications/all',
    STATS: '/verifications/stats',
    REVIEW: (id: string) => `/verifications/${id}/review`,
    ESCALATE: (id: string) => `/verifications/${id}/escalate`,
    EMPLOYMENT_CONTACT: (id: string) => `/verifications/${id}/employment-contact`,
    EMPLOYMENT_RESPONSE: (token: string) => `/verifications/employment-response/${token}`,
    SET_SLA: (id: string) => `/verifications/${id}/sla`,
    SET_APPROVAL_CHAIN: (id: string) => `/verifications/${id}/approval-chain`,
    APPROVE_LEVEL: (id: string) => `/verifications/${id}/approve-level`,
  },
  SAVED_SEARCHES: {
    CREATE: '/saved-searches',
    LIST: '/saved-searches',
    UPDATE: (id: string) => `/saved-searches/${id}`,
    DELETE: (id: string) => `/saved-searches/${id}`,
  },
  SEARCH: {
    AUTOCOMPLETE: '/search/autocomplete',
    SUGGEST: '/search/suggest',
    SUGGEST_SKILLS: '/search/suggest/skills',
    SUGGEST_LOCATIONS: '/search/suggest/locations',
    SUGGEST_COMPANIES: '/search/suggest/companies',
    SUGGEST_TITLES: '/search/suggest/titles',
    DID_YOU_MEAN: '/search/did-you-mean',
    HISTORY: '/search/history',
    POPULAR: '/search/popular',
    FIELD_HISTORY: (field: string) => `/search/field-history/${field}`,
  },
  FEATURE_FLAGS: {
    CLIENT: '/feature-flags/client',
    ALL: '/feature-flags',
  },
  WEBAUTHN: {
    REGISTER_OPTIONS: '/webauthn/register/options',
    REGISTER_VERIFY: '/webauthn/register/verify',
    LOGIN_OPTIONS: '/webauthn/login/options',
    LOGIN_VERIFY: '/webauthn/login/verify',
    CREDENTIALS: '/webauthn/credentials',
  },
  WEBHOOKS: {
    BASE: '/webhooks',
    DETAIL: (id: string) => `/webhooks/${id}`,
    DELIVERIES: (id: string) => `/webhooks/${id}/deliveries`,
    TEST: (id: string) => `/webhooks/${id}/test`,
  },
  CANDIDATES_EXTRA: {
    PARSE_RESUME: '/candidates/me/resume/parse',
    PARSED_RESUME: '/candidates/me/resume/parsed',
    ANALYTICS: '/candidates/me/analytics',
    ANALYTICS_EXPORT: '/candidates/me/analytics/export',
    JOB_ALERTS: '/candidates/me/job-alerts',
    JOB_ALERT_DETAIL: (id: string) => `/candidates/me/job-alerts/${id}`,
    JOB_ALERT_MATCHES: (id: string) => `/candidates/me/job-alerts/${id}/matches`,
  },
  RECOMMENDATIONS: {
    JOBS: '/recommendations/jobs',
    CANDIDATES: (jobId: string) => `/recommendations/candidates/${jobId}`,
    CANDIDATES_FOR_EMPLOYER: '/recommendations/candidates',
    DISMISS_JOB: (jobId: string) => `/recommendations/jobs/${jobId}/dismiss`,
  },
  ADVANCED_ANALYTICS: {
    USER_GROWTH: '/analytics/advanced/user-growth',
    APPLICATION_FUNNEL: '/analytics/advanced/application-funnel',
    POPULAR_SKILLS: '/analytics/advanced/popular-skills',
    SALARY_TRENDS: '/analytics/advanced/salary-trends',
    JOB_TRENDS: '/analytics/advanced/job-trends',
  },
  CONTACT: {
    SUBMIT: '/contact',
  },
  TICKETS: {
    CREATE: '/tickets',
    GUEST_CREATE: '/tickets/guest',
    MY_TICKETS: '/tickets/my-tickets',
    ALL: '/tickets/all',
    DETAIL: (id: string) => `/tickets/${id}`,
    BY_NUMBER: (num: string) => `/tickets/by-number/${num}`,
    MESSAGES: (id: string) => `/tickets/${id}/messages`,
    ASSIGN: (id: string) => `/tickets/${id}/assign`,
    STATUS: (id: string) => `/tickets/${id}/status`,
    CLOSE: (id: string) => `/tickets/${id}/close`,
    REOPEN: (id: string) => `/tickets/${id}/reopen`,
    SATISFACTION: (id: string) => `/tickets/${id}/satisfaction`,
    AGENTS: '/tickets/agents',
    STATS: '/tickets/stats',
    ANALYTICS: '/tickets/analytics',
  },
  CONFIG: {
    OTP: '/config/otp',
    SECURITY: '/config/security',
  },
  PUBLIC_STATS: '/public/stats',
  PUBLIC_JOB_CATEGORY_COUNTS: '/public/jobs/category-counts',
  HEALTH: '/health',
} as const;
