export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    HELP: '/help',
    /**
     * Human-readable site map page. URL is `/site-map` (dashed) because the
     * undashed `/sitemap` conflicts with the `sitemap.xml` metadata file —
     * having both an `app/sitemap/` folder (route segment) and an
     * `app/sitemap.ts` (metadata file) causes Next.js to drop the `.xml`
     * index. Renaming the HTML route removes the shadow without touching
     * the XML sitemap.
     */
    SITEMAP: '/site-map',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    COOKIE_POLICY: '/cookie-policy',
    REFUND_POLICY: '/refund-policy',
    ACCESSIBILITY: '/accessibility',
    DISCLAIMER: '/disclaimer',
    COMPANY: (id: string) => `/company/${id}`,
    JOBS: '/jobs',
    JOB_DETAIL: (slug: string) => `/jobs/${slug}`,
    JOBS_BY_CITY: (city: string) => `/jobs/in/${city}`,
    JOBS_BY_CATEGORY: (cat: string) => `/jobs/category/${cat}`,
    JOBS_BY_DEPARTMENT: (dept: string) => `/jobs/department/${dept}`,
    JOBS_BY_QUALIFICATION: (qual: string) => `/jobs/qualification/${qual}`,
    JOBS_BY_COLLECTION: (coll: string) => `/jobs/collection/${coll}`,
    JOBS_ROLE_CITY: (role: string, city: string) => `/jobs/${role}-jobs-in-${city}`,
    JOBS_ROLE_EXP: (role: string, years: number) =>
      `/jobs/${role}-jobs-for-${years}-years-experience`,
    COMPANIES: '/companies',
    COMPANY_PUBLIC: (slug: string) => `/companies/${slug}`,
    COMPANIES_BY_CATEGORY: (cat: string) => `/companies/category/${cat}`,
    COMPANIES_BY_CITY: (city: string) => `/companies/in/${city}`,
    COMPANIES_BY_INDUSTRY: (ind: string) => `/companies/industry/${ind}`,
    COMPANIES_BY_COLLECTION: (coll: string) => `/companies/collection/${coll}`,
  },
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_CANDIDATE: '/auth/login/candidate',
    LOGIN_EMPLOYER: '/auth/login/employer',
    REGISTER: '/auth/register',
    REGISTER_CANDIDATE: '/auth/register/candidate',
    REGISTER_EMPLOYER: '/auth/register/employer',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
  },
  CANDIDATE: {
    DASHBOARD: '/candidate',
    ONBOARDING: '/candidate/onboarding',
    ANALYTICS: '/candidate/analytics',
    PROFILE: '/candidate/profile',
    PROFILE_PREVIEW: '/candidate/profile/preview',
    JOBS: '/candidate/jobs',
    JOB_DETAIL: (id: string) => `/candidate/jobs/${id}`,
    RECOMMENDATIONS: '/candidate/recommendations',
    APPLICATIONS: '/candidate/applications',
    APPLICATION_DETAIL: (id: string) => `/candidate/applications/${id}`,
    SAVED_JOBS: '/candidate/saved-jobs',
    JOB_ALERTS: '/candidate/job-alerts',
    VERIFICATION: '/candidate/verification',
    SETTINGS: '/candidate/settings',
    HELP: '/candidate/help',
    TICKET_DETAIL: (id: string) => `/candidate/help/${id}`,
  },
  EMPLOYER: {
    DASHBOARD: '/employer',
    ONBOARDING: '/employer/onboarding',
    PROFILE: '/employer/profile',
    POST_JOB: '/employer/jobs/new',
    MY_JOBS: '/employer/jobs',
    JOB_DETAIL: (id: string) => `/employer/jobs/${id}`,
    JOB_EDIT: (id: string) => `/employer/jobs/${id}/edit`,
    JOB_APPLICATIONS: (id: string) => `/employer/jobs/${id}/applications`,
    APPLICATIONS: '/employer/applications',
    APPLICATION_DETAIL: (id: string) => `/employer/applications/${id}`,
    CANDIDATES: '/employer/candidates',
    CANDIDATE_DETAIL: (id: string) => `/employer/candidates/${id}`,
    SAVED_CANDIDATES: '/employer/candidates/saved',
    TEAM: '/employer/team',
    ANALYTICS: '/employer/analytics',
    PROFILE_PREVIEW: '/employer/profile/preview',
    VERIFICATION: '/employer/verification',
    SETTINGS: '/employer/settings',
    HELP: '/employer/help',
    TICKET_DETAIL: (id: string) => `/employer/help/${id}`,
    ASSISTED_HIRING: '/employer/assisted-hiring',
    // Vendor Connect capability (employers with the VENDOR_CONNECT plan).
    VENDOR_HUB: '/employer/vendor',
    VENDOR_PROFILE: '/employer/vendor/profile',
    VENDOR_LEADS: '/employer/vendor/leads',
    VENDOR_JOBS: '/employer/vendor/jobs',
    // Requests this employer SENT to recruitment partners (any employer).
    VENDOR_REQUESTS: '/employer/vendor/requests',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    JOBS: '/admin/jobs',
    JOB_DETAIL: (id: string) => `/admin/jobs/${id}`,
    VERIFICATIONS: '/admin/verifications',
    ANALYTICS: '/admin/analytics',
    AUDIT_LOGS: '/admin/audit-logs',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
    TICKETS: '/admin/tickets',
    TICKET_DETAIL: (id: string) => `/admin/tickets/${id}`,
    MODERATION: '/admin/moderation',
    APPLICATIONS: '/admin/applications',
    EMAIL_TEMPLATES: '/admin/email-templates',
  },
  SUPER_ADMIN: {
    DASHBOARD: '/super-admin',
    ADMINS: '/super-admin/admins',
    ADMIN_DETAIL: (id: string) => `/super-admin/admins/${id}`,
    USERS: '/super-admin/users',
    USER_DETAIL: (id: string) => `/super-admin/users/${id}`,
    RESUME_WATERMARK: '/super-admin/resume-watermark',
    JOBS: '/super-admin/jobs',
    JOB_NEW: '/super-admin/jobs/new',
    JOB_DETAIL: (id: string) => `/super-admin/jobs/${id}`,
    JOB_EDIT: (id: string) => `/super-admin/jobs/${id}/edit`,
    WHATSAPP: '/super-admin/whatsapp',
    WHATSAPP_TEMPLATES: '/super-admin/whatsapp/templates',
    WHATSAPP_CONTACTS: '/super-admin/whatsapp/contacts',
    WHATSAPP_PLATFORM_USERS: '/super-admin/whatsapp/platform-users',
    WHATSAPP_CAMPAIGNS: '/super-admin/whatsapp/campaigns',
    WHATSAPP_CAMPAIGN_NEW: '/super-admin/whatsapp/campaigns/new',
    WHATSAPP_CAMPAIGN_DETAIL: (id: string) => `/super-admin/whatsapp/campaigns/${id}`,
    WHATSAPP_ANALYTICS: '/super-admin/whatsapp/analytics',
    WHATSAPP_SETTINGS: '/super-admin/whatsapp/settings',
    EMAIL: '/super-admin/email',
    EMAIL_TEMPLATES: '/super-admin/email/templates',
    EMAIL_CONTACTS: '/super-admin/email/contacts',
    EMAIL_CONTACT_DETAIL: (id: string) => `/super-admin/email/contacts/${id}`,
    EMAIL_SETS: '/super-admin/email/sets',
    EMAIL_UNSUBSCRIBES: '/super-admin/email/unsubscribes',
    EMAIL_PLATFORM_USERS: '/super-admin/email/platform-users',
    EMAIL_CAMPAIGNS: '/super-admin/email/campaigns',
    EMAIL_CAMPAIGN_NEW: '/super-admin/email/campaigns/new',
    EMAIL_CAMPAIGN_DETAIL: (id: string) => `/super-admin/email/campaigns/${id}`,
    EMAIL_ANALYTICS: '/super-admin/email/analytics',
    EMAIL_SUPPRESSION: '/super-admin/email/suppression',
    EMAIL_SETTINGS: '/super-admin/email/settings',
    EMAIL_MAIL: '/super-admin/email/mail',
    ANALYTICS: '/super-admin/analytics',
    FEATURE_FLAGS: '/super-admin/feature-flags',
    CONFIG: '/super-admin/config',
    TICKETS: '/super-admin/tickets',
    SETTINGS: '/super-admin/settings',
  },
  PORTAL: {
    LOGIN: '/portal/login',
  },
  BILLING: {
    PRICING: '/pricing',
    PRICING_EMPLOYER: '/pricing/employer',
    PRICING_CANDIDATE: '/pricing/candidate',
    ORDERS: '/billing/orders',
    ORDER_DETAIL: (id: string) => `/billing/orders/${id}`,
    INVOICES: '/billing/invoices',
    INVOICE_DETAIL: (id: string) => `/billing/invoices/${id}`,
    SUBSCRIPTIONS: '/billing/subscriptions',
    SUBSCRIPTION_DETAIL: (id: string) => `/billing/subscriptions/${id}`,
    PAYMENT_METHODS: '/billing/payment-methods',
    CREDITS: '/billing/credits',
    /** "My Plans" master page — every plan the user currently holds. */
    MY_PLANS: '/billing/plans',
    /** Per-category detail (JOB_POST / CV_DATABASE / ...). */
    PLAN_CATEGORY: (category: string) => `/billing/plans/${category.toLowerCase()}`,
    /** Per-plan detail, nested under its category. */
    PLAN_DETAIL: (category: string, planCode: string) =>
      `/billing/plans/${category.toLowerCase()}/${encodeURIComponent(planCode)}`,
    CHECKOUT: (planCode: string) => `/billing/checkout/${planCode}`,
    RESUME_CHECKOUT: (orderId: string) => `/billing/checkout/order/${orderId}`,
    UPGRADE: (planCode: string) => `/billing/upgrade/${planCode}`,
    QUOTE: '/billing/quote',
    QUOTE_DETAIL: (id: string) => `/billing/quote/${id}`,
    CANCEL_SUBSCRIPTION: (subId: string) => `/billing/cancel?id=${encodeURIComponent(subId)}`,
  },
  NOTIFICATIONS: '/notifications',
  VENDORS_PUBLIC: {
    LIST: '/vendors',
    DETAIL: (slug: string) => `/vendors/${slug}`,
  },
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.PUBLIC.HOME,
  ROUTES.PUBLIC.ABOUT,
  ROUTES.PUBLIC.CONTACT,
  ROUTES.PUBLIC.HELP,
  ROUTES.PUBLIC.PRIVACY,
  ROUTES.PUBLIC.TERMS,
  ROUTES.PUBLIC.COOKIE_POLICY,
  ROUTES.PUBLIC.REFUND_POLICY,
  ROUTES.PUBLIC.ACCESSIBILITY,
  ROUTES.PUBLIC.DISCLAIMER,
  ROUTES.VENDORS_PUBLIC.LIST,
  // Public job + company surfaces (Phase 21).
  ROUTES.PUBLIC.JOBS,
  ROUTES.PUBLIC.COMPANIES,
];

export const AUTH_ROUTES = [
  ROUTES.AUTH.LOGIN,
  ROUTES.AUTH.LOGIN_CANDIDATE,
  ROUTES.AUTH.LOGIN_EMPLOYER,
  ROUTES.AUTH.REGISTER,
  ROUTES.AUTH.REGISTER_CANDIDATE,
  ROUTES.AUTH.REGISTER_EMPLOYER,
  ROUTES.AUTH.FORGOT_PASSWORD,
  ROUTES.AUTH.RESET_PASSWORD,
  ROUTES.AUTH.VERIFY_EMAIL,
  ROUTES.PORTAL.LOGIN,
];

export const ROLE_DASHBOARDS = {
  CANDIDATE: ROUTES.CANDIDATE.DASHBOARD,
  EMPLOYER: ROUTES.EMPLOYER.DASHBOARD,
  ADMIN: ROUTES.ADMIN.DASHBOARD,
  SUPER_ADMIN: ROUTES.SUPER_ADMIN.DASHBOARD,
} as const;
