# ============================================================
# PostgreSQL — Network Policy
# Only backend can connect. No external egress.
# ============================================================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-netpol
  namespace: hire-adda
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - port: 5432
          protocol: TCP
    # Allow backup CronJobs
    - from:
        - podSelector:
            matchLabels:
              app: db-backup
      ports:
        - port: 5432
          protocol: TCP
  egress:
    # DNS only
    - to: []
      ports:
        - port: 53
          protocol: UDP
